# -*- coding: utf-8 -*-
"""project_pnenumonia_or_normal (2).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c7X3QciDDda21QurX3Jn3pKNAurtJtNL
"""

!kaggle datasets download -d paultimothymooney/chest-xray-pneumonia

!unzip -q "/content/chest-xray-pneumonia.zip"

import os
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator

# Define paths
train_dir = "/content/chest_xray/train"
validation_dir = "/content/chest_xray/val"
test_dir = "/content/chest_xray/test"

# Data augmentation and normalization for training
train_datagen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=20,
    width_shift_range=0.2,
    height_shift_range=0.2,
    shear_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True,
    fill_mode='nearest')

# Normalization for validation and testing
validation_datagen = ImageDataGenerator(rescale=1./255)
test_datagen = ImageDataGenerator(rescale=1./255)

# Define batch size
batch_size = 32

# Flow training images in batches using train_datagen generator
train_generator = train_datagen.flow_from_directory(
    train_dir,
    target_size=(150, 150),
    batch_size=batch_size,
    class_mode='binary')

# Flow validation images in batches using validation_datagen generator
validation_generator = validation_datagen.flow_from_directory(
    validation_dir,
    target_size=(150, 150),
    batch_size=batch_size,
    class_mode='binary')

# Flow test images in batches using test_datagen generator
test_generator = test_datagen.flow_from_directory(
    test_dir,
    target_size=(150, 150),
    batch_size=batch_size,
    class_mode='binary')

# Display class labels
print("Class labels:", train_generator.class_indices)

# Example of how to use these generators with a CNN model in TensorFlow/Keras
# Define and compile your CNN model
model = tf.keras.models.Sequential([
    tf.keras.layers.Conv2D(32, (3, 3), activation='relu', input_shape=(150, 150, 3)),
    tf.keras.layers.MaxPooling2D(2, 2),
    tf.keras.layers.Conv2D(64, (3, 3), activation='relu'),
    tf.keras.layers.MaxPooling2D(2, 2),
    tf.keras.layers.Conv2D(128, (3, 3), activation='relu'),
    tf.keras.layers.MaxPooling2D(2, 2),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(512, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])
# Calculate steps per epoch
steps_per_epoch_train = train_generator.samples // batch_size
steps_per_epoch_validation = validation_generator.samples // batch_size

# Ensure at least one step per epoch
if steps_per_epoch_train == 0:
    steps_per_epoch_train = 1
if steps_per_epoch_validation == 0:
    steps_per_epoch_validation = 1

# Train the model
history = model.fit(
    train_generator,
    steps_per_epoch=steps_per_epoch_train,
    epochs=10,
    validation_data=validation_generator,
    validation_steps=steps_per_epoch_validation)





# Evaluate the model on the test set
test_loss, test_acc = model.evaluate(test_generator, steps=test_generator.samples // batch_size)
print("Test Accuracy:", test_acc)

# Check if the training directory contains images
num_train_samples = sum(len(files) for _, _, files in os.walk(train_dir))
print("Number of training samples:", num_train_samples)

# Check the value of train_generator.samples
print("Number of training generator samples:", train_generator.samples)

# Evaluate the model on the test set
test_loss, test_acc = model.evaluate(test_generator, steps=test_generator.samples // batch_size)
print("Test Loss:", test_loss)
print("Test Accuracy:", test_acc)

from tensorflow.keras.preprocessing import image
import numpy as np

# Path to the image you want to test
image_path = "/content/image 2.jpg"  # Replace this with the path to your image

# Load and preprocess the image
img = image.load_img(image_path, target_size=(150, 150))
img_array = image.img_to_array(img)
img_array = np.expand_dims(img_array, axis=0)
img_array = img_array / 255.0  # Normalize the image

# Predict the class probabilities
predictions = model.predict(img_array)

# Print the predicted class probabilities
print("Predictions:", predictions)

# Predict the class probabilities
predictions = model.predict(img_array)

# Interpret the predictions
if predictions[0] < 0.5:
    print("Predicted: Normal")
else:
    print("Predicted: Pneumonia")

from google.colab import drive
drive.mount('/content/drive')

model.save("/content/drive/MyDrive/hafsa-model.h5")

from tensorflow.keras.preprocessing import image
import numpy as np

# Path to the image you want to test
image_path = "/content/chest_xray/test/PNEUMONIA/person100_bacteria_477.jpeg"  # Replace this with the path to your image

# Load and preprocess the image
img = image.load_img(image_path, target_size=(150, 150))
img_array = image.img_to_array(img)
img_array = np.expand_dims(img_array, axis=0)
img_array = img_array / 255.0  # Normalize the image

# Predict the class probabilities
predictions = model.predict(img_array)

# Print the predicted class probabilities
print("Predictions:", predictions)

# Predict the class probabilities
predictions = model.predict(img_array)

# Interpret the predictions
if predictions[0] < 0.5:
    print("Predicted: Normal")
else:
    print("Predicted: Pneumonia")

from tensorflow.keras.preprocessing import image
import numpy as np

def save_pneumonia_result_txt(detected, confidence):
    """ Pneumonia detection result ko TXT file me save karega """
    # Files ke naam
    positive_file = "pneumonia_positive.txt"
    negative_file = "pneumonia_negative.txt"

    # Pneumonia related information
    pneumonia_info = {
        "X-ray Findings": "Lung opacity, Consolidation, Infiltrates" if detected else "Clear lungs, No abnormal opacities",
        "Precautions": "Vaccination, Hygiene, Avoid smoking" if detected else "Maintain hygiene, Regular checkups",
        "Treatment": "Antibiotics, Oxygen therapy, Rest" if detected else "No treatment needed, Stay healthy"
    }

    # Select correct file
    filename = positive_file if detected else negative_file

    # Write data to TXT file
    with open(filename, "a") as file:  # Append mode
        file.write(f"Pneumonia_Detected: {'Yes' if detected else 'No'}\n")
        file.write(f"Confidence Score: {confidence:.2f}\n")
        file.write(f"X-ray Findings: {pneumonia_info['X-ray Findings']}\n")
        file.write(f"Precautions: {pneumonia_info['Precautions']}\n")
        file.write(f"Treatment: {pneumonia_info['Treatment']}\n")
        file.write("------------------------------------------------\n")

    print(f"TXT file updated for {'positive' if detected else 'negative'} cases")

# Path to the image you want to test
image_path = "/content/chest_xray/test/PNEUMONIA/person100_bacteria_477.jpeg"  # Replace this with your image path

# Load and preprocess the image
img = image.load_img(image_path, target_size=(150, 150))
img_array = image.img_to_array(img)
img_array = np.expand_dims(img_array, axis=0)
img_array = img_array / 255.0  # Normalize the image

# Predict the class probabilities
predictions = model.predict(img_array)

# Confidence score (probability of pneumonia)
confidence = float(predictions[0])

# Interpret the predictions
if confidence >= 0.5:
    print("Predicted: Pneumonia")
    save_pneumonia_result_txt(True, confidence)
else:
    print("Predicted: Normal")
    save_pneumonia_result_txt(False, confidence)

